import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

function LandingScreen({
  createGame,
  joinGame,
  gameIdInput,
  setGameIdInput,
  userName,
  setUserName,
}) {

  //this css are generated by gemini ai for the purpose of learning tailwind css
  return (
    <div className="fixed inset-0 flex items-center justify-center">
      <div className="flex flex-col gap-3 p-3 ">
        
         <h1 className="pb-10 text-7xl">
        Enter Information
        </h1>

        <div className="flex items-center gap-3 pl-10">
        <input
          type="text"
          placeholder="Your Name"
          className="p-2 rounded border-none bg-gray700 text-white placeholder-gray-400"
          value={userName}
          onChange={(e) => setUserName(e.target.value)}
        ></input>

        <button 
          onClick={createGame} 
          disabled={!userName} 
          className="p-2 px-4 rounded bg-pink-400 text-black font-semibold hover:bg-pink-500 disabled:opacity-50"
          >
            Create New Game (Host)
          </button>
        </div>
      
      <div className="flex items-center gap-3 pl-10">
        <input
        type="text"
        placeholder="Enter Game Id to Join"
        className="p-2 rounded border-none bg-gray-700 text-white placeholder-gray-400"
        value={gameIdInput}
        onChange={(e) => setGameIdInput(e.target.value)}
      ></input>
      
      <button
        onClick={joinGame}
        disabled={!gameIdInput || gameIdInput.length !== 6 || !userName}
        className="p-2 px-4 rounded bg-blue-700 text-white font-semibold hover:bg-blue-800 disabled:opacity-50"
      >
        Join Game
      </button>
      </div>

      </div>
    </div>
  );
}

export default LandingScreen;
